appID: "gftdnn"
name: "Deep Learning Loss Predictor"
description: "An insurance loss predictor that uses a deep neural network to estimate the payout for claims"
owner: "giorgio"
namespace: "giorgioproject"
types:
 - playbook


metrics:
  - owner: "$owner$"
    name: "rmse"
    metricClassname: "Double"
    summary: "Root Mean Squared Error (RMSE) is a measure of the difference between a true and predicted value." 
    maximumValue: 1.0
    minimumValue: 0.0
    higherIsBetter: False
    displayUnit: "RMSE"
  - owner: "$owner$"
    name: "costPerHour"
    metricClassname: "Double"
    summary: "The cost of running this Pod per hour in US dollars." 
    maximumValue: 1000.0
    minimumValue: 0.0
    higherIsBetter: True
    displayUnit: "$/hour"

objects:
  - appID: "$appID$"
    owner: "$owner$"
    objectID: "dnn-train"
    type: Job
    yamlSource:
      kind: Job
      apiVersion: batch/v1
      metadata:
        name: $appID$-$objectID$-$instance$
        namespace: $namespace$
        labels:
          app: $appID$
      spec:
        parallelism: 1
        completions: 1
        backoffLimit: 3
        template:
          metadata:
            labels:
              app: $appID$
          spec:
            nodeSelector:
              node-role.ida/gpu2080ti: 'true'
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            containers:
              - resources:
                 limits:
                    cpu: '5000m'
                    memory: 32Gi
                    nvidia.com/gpu: '1'
                 requests:
                    cpu: '2'
                    memory: 16Gi
                    nvidia.com/gpu: '1'
                name: losspredictortraining
                command:
                  - python
                imagePullPolicy: Always
                volumeMounts:
                  - name: nfs-access
                    mountPath: /nfs/
                terminationMessagePolicy: File
                image: 'giorgioroffo/deeplearning.ai:tf15-py36-all'
                workingDir: /nfs/GFTInsuranceData/
                args:
                  - 'GFTDNN.py'
                  - '-I'
                  - '/nfs/GFTInsuranceData/GFT_dataset/'
                  - '-O'
                  - '/nfs/GFTInsuranceData/results/'
                ports:
                  - name: promexporter
                    containerPort: 8000   
                    protocol: TCP
                env:
                  - name: "GFT_PCA_enabled"
                    value: "$GFT_PCA_enabled$"
                  - name: "GFT_normed_resp"
                    value: "$GFT_normed_resp$"
                  - name: "GFT_NUM_UNITS"
                    value: "$GFT_NUM_UNITS$"
                  - name: "GFT_BATCH_SIZE"
                    value: "$GFT_BATCH_SIZE$"
                  - name: "GFT_topKpc"
                    value: "$GFT_topKpc$"
                  - name: "GFT_EPOCHS"
                    value: "$GFT_EPOCHS$"
                  - name: "GFT_loss_func"
                    value: "$GFT_loss_func$"
                  - name: "GFT_dropout_rate"
                    value: "$GFT_dropout_rate$"
                  - name: "GFT_initial_learning_rate"
                    value: "$GFT_initial_learning_rate$"
                  - name: "GFT_decay_steps"
                    value: "$GFT_decay_steps$"
                  - name: "GFT_decay_rate"
                    value: "$GFT_decay_rate$"
                  - name: "GFT_l1_reg"
                    value: "$GFT_l1_reg$"
                  - name: "GFT_l2_reg"
                    value: "$GFT_l2_reg$"
                  - name: "GFT_name_net_export"
                    value: "$GFT_name_net_export$"
                  - name: "GFT_num_folds"
                    value: "$GFT_num_folds$"
                  - name: "appID"
                    value: "$appID$"
                  - name: "instance"
                    value: "$instance$"
                  - name: "objectID"
                    value: "$objectID$"
                  - name: "owner"
                    value: "$owner$"
                  - name: "namespace"
                    value: "$namespace$"
            serviceAccount: containerroot
            volumes:
              - name: nfs-access
                persistentVolumeClaim:
                  claimName: giorgiovol1claim
            dnsPolicy: ClusterFirst

sequences:
  - appID: "$appID$"
    owner: "$owner$"
    namespace: "$namespace$"
    sequenceID: "train"
    name: "Loss Predictor Model Training"
    description: "Deploys a instance of the model training with a number of parameters. Sequence will copy validation performance metrics into the central database until the learning job ends."
    parameters:
      GFT_PCA_enabled: 'True'
      GFT_normed_resp: 'True'
      GFT_NUM_UNITS: '400'
      GFT_BATCH_SIZE: '256'
      GFT_topKpc: '20'
      GFT_EPOCHS: '5'
      GFT_loss_func: 'mae'
      GFT_dropout_rate: '0.4'
      GFT_initial_learning_rate: '5e-1'
      GFT_decay_steps: '20000'
      GFT_decay_rate: '0.9'
      GFT_l1_reg: '0.01'
      GFT_l2_reg: '0.01'
      GFT_name_net_export: '_ANN_5layers_'
      GFT_num_folds: '10'
    operations:
      - className: Instantiate
        objectID: "dnn-train"
        defineInstanceRef: "trainingInstance"
      - className: SetSequenceParameters
        instanceRef: "trainingInstance"
      - className: Apply
        instanceRef: "trainingInstance"
      - className: NewMetricValues
        instanceRef: "trainingInstance"
        metrics: 
          - "rmse"
          - "costPerHour"
      - className: RecordMetricsUntil
        metrics:
          - "rmse"
          - "costPerHour"
        instanceRef: "trainingInstance"
        waitForStatus: "Complete"
        gracePeriodSec: 30
    mode: Continue