appID: "twitterml"
name: "Tweet Classifier (Java)"
description: "This application trains a Twitter machine learning classifier based on the Weka toolkit in Java and write the model to disk. Tweets are held on GZIP format on the NFS. "
owner: "$owner$"
namespace: "$namespace$"
types:
 - playbook
 - inferMissingValues
 - overrideValues
 - setObjectMetadata


objects:
  - objectID: "twitterml"
    yamlSource:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: job-trecis-smolearning-#0
        namespace: richardmproject
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            labels:
              app: trecis-smolearning
          spec:
            containers:
            - name: smolearning
              image: 'openjdk:8'
              resources:
                requests:
                  cpu: "$request-cpu$"
                  memory: "$request-mem$"
                limits:
                  cpu: "$limit-cpu$"
                  memory: "$limit-mem$"
              volumeMounts:
                - mountPath: /nfs/
                  name: nfs-access
              imagePullPolicy: IfNotPresent
              workingDir: /nfs/TwitterMLExample/TREC-IS-System/
              command:
                - 'java'
              args:
                - '-jar'
                - 'target/trecis-system-1.0-SNAPSHOT.jar'
              env:
                - name: "owner"
                  value: "$owner$"
                - name: "appID"
                  value: "$appID$"
                - name: "instance"
                  value: "$instance$"
                - name: "objectID"
                  value: "$objectID$"
                - name: 'TRECIS_CLASSFILE'
                  value: $trecis-classfile$
                - name: 'TRECIS_OUTDIR'
                  value: $trecis-outdir$
                - name: 'TRECIS_BATCHSIZE'
                  value: $trecis-batchsize$
                - name: 'TRECIS_EPSILON'
                  value: $trecis-epsilon$
                - name: 'TRECIS_C'
                  value: $trecis-c$
            volumes:
            - name: nfs-access
              persistentVolumeClaim:
                claimName: richardmvol1claim
            restartPolicy: Never

sequences:
  - appID: "$appID$"
    owner: "$owner$"
    namespace: "$namespace$"
    sequenceID: "train"
    name: "Train TREC-IS Model"
    description: "Launches a training job for a TREC-IS tweet classification model. "
    parameters:
      request-cpu: "500m"
      request-mem: "1Gi"
      limit-cpu: "500m"
      limit-mem: "1Gi"
      trecis-classfile: "ContinuingNews.arff"
      trecis-outdir: "resources/models/smolearning-$random$"
      trecis-batchsize: "50"
      trecis-epsilon: "1.0E-11"
      trecis-c: "1.0"
    operations:
      - className: Instantiate
        objectID: "twitterml"
        defineInstanceRef: "twittermlInstance"
      - className: SetSequenceParameters
        instanceRef: "twittermlInstance"
      - className: Apply
        instanceRef: "twittermlInstance"
    mode: Continue