appID: "grssr"
name: "Grocery Recommender System (M18 Review Version)"
description: >
  This is an example grocery recommender system.
owner: "$owner$"
namespace: "$namespace$"
types:
 - playbook
 - inferMissingValues
 - overrideValues
 - setObjectMetadata


objects:
  # Deployment Config: recommender
  - objectID: "recommender"
    yamlSource:
      kind: DeploymentConfig
      apiVersion: apps.openshift.io/v1
      metadata:
        labels:
          app: recommender
      spec:
        triggers:
          - type: ConfigChange
        replicas: 1
        selector:
          app: recommender
        template:
          metadata:
            labels:
              app: recommender
          spec:
            containers:
              - name: recommender
                image: >-
                  jdtotow/recommender:latest
                env:
                 - name: LOGSTASHURL
                   value: "http://logstash.tme.svc.cluster.local:8081"
                 - name: appID
                   value: $appID$
                 - name: objectID
                   value: $objectID$
                 - name: instance
                   value: $instance$
                ports:
                  - name: "tcp-7070"
                    containerPort: 7070
                    protocol: TCP
                resources: {}
                imagePullPolicy: Always
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
  
  # Service: srv-recommender
  - objectID: "srv-recommender"
    yamlSource:
      kind: Service
      apiVersion: v1
      metadata:
        labels:
          app: recommender
      spec:
        ports:
          - name: 7070-tcp
            protocol: TCP
            port: 7070
            targetPort: 7070
        selector:
          app: recommender
        type: ClusterIP

sequences:
  - sequenceID: "launch"
    name: "Launch Recommender Service"
    appID: "$appID$"
    owner: "$owner$"
    namespace: "$namespace$"
    description: "Deploys the recommender service container on the cluster along with its network service"
    parameters: {}
    operations:
      # Steps for creating the deployment config
      - className: Instantiate # Spawn a new copy from the template
        objectID: "recommender"
        defineInstanceRef: "recI"
      - className: SetSequenceParameters # Fill in any missing placeholders
        instanceRef: "recI"
      - className: Apply # Create deployment config on the cluster
        instanceRef: "recI"
      - className: WaitFor # Wait until the deployment config is reporting available
        instanceRef: "recI"
        waitForStatus: "Available"
      # Now create the service
      - className: Instantiate # Spawn a new copy from the template
        objectID: "srv-recommender"
        defineInstanceRef: "recS"
      - className: Apply # Create the service on the cluster
        instanceRef: "recS"
    mode: Continue