appID: "gdtdefaultapp"
owner: "gdt"

objectID: "prometheussa"
type: ServiceAccount

yamlSource:
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: $objectID$-$instance$
    namespace: $namespace$