owner: richardm
objectID: "prometheusconfig"
type: ConfigMap

yamlSource:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: $objectID$
    namespace: $namespace$
  data:
    prometheus.env.yaml: >
      global:
        scrape_interval:     15s
        external_labels:
          monitor: 'codelab-monitor'
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9090']
        - job_name: gdt/$namespace$
          metrics_path: /
          honor_labels: true
          kubernetes_sd_configs:
           - role: pod
             namespaces:
               names:
                - $namespace$
          relabel_configs:
           - source_labels: [__meta_kubernetes_pod_ready]
             separator: ;
             regex: true
             replacement: $1
             action: keep
           - source_labels: [__meta_kubernetes_pod_container_port_name]
             separator: ;
             regex: promexporter
             replacement: $1
             action: keep
          scrape_interval: 30s
          scheme: https
          tls_config:
            insecure_skip_verify: false
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token