appID: "gdtdefaultapp"
owner: "richardm"

objectID: "prometheusrole"
type: Role

yamlSource:
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: $objectID$
    namespace: $namespace$
  rules:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - ''
      resources:
        - nodes
        - services
        - endpoints
        - pods