apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: realizationstatedb
  namespace: realization
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: realization
        deploymentconfig: realizationstatedb
    spec:
      containers:
      - name: realizationstatedb
        image: mysql:latest
        resources:
          requests:
            cpu: "1000m"
            memory: "8Gi"
          limits:
            cpu: "2000m"
            memory: "16Gi"
        ports:
          - containerPort: 6603
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /var/lib/mysql/
            name: database-volume
        env:
         - name: "MYSQL_ALLOW_EMPTY_PASSWORD"
           value: "true"
      securityContext: {}
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: realizationstatedbclaim

