apiVersion: v1
kind: DeploymentConfig
metadata:
  name: realizationstatedb
  namespace: realization
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: realization
        deploymentconfig: realizationstatedb
    spec:
      containers:
      - name: realizationstatedb
        image: mongo:4.0.4
        resources:
          requests:
            cpu: "1000m"
            memory: "8Gi"
          limits:
            cpu: "2000m"
            memory: "16Gi"
        ports:
          - containerPort: 27017
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /data/db/
            name: database-volume
      securityContext: {}
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: realizationstatedbclaim

