apiVersion: v1
kind: Service
metadata:
  name: srv-realizationstatedb
  namespace: realization      
spec:
  selector:                  
    deploymentconfig: realizationstatedb  
  ports:
  - name: mongodb
    port: 3306               
    protocol: TCP
    targetPort: 3306  
