kind: ConfigMap
apiVersion: v1
metadata:
  name: realizationdbconf
  namespace: NAMESPACE
data:
  my.cnf: |-
    [mysqld]
    user      = mysql
    pid-file  = /var/run/mysqld/mysqld.pid
    socket    = /var/run/mysqld/mysqld.sock
    port      = 3306
    basedir   = /usr
    datadir   = /var/lib/mysql
    tmpdir    = /tmp
    bind-address = 0.0.0.0
    secure-file-priv=NULL