kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: realizationstatedb
  namespace: NAMESPACE
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 1
  test: false
  selector:
    app: realization
    deploymentconfig: realizationstatedb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: realization
        deploymentconfig: realizationstatedb
    spec:
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: realizationdbclaim
        - name: database-conf
          configMap:
            name: realizationdbconf
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 16Gi
            requests:
              cpu: '1'
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          name: realizationstatedb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: MYSQLPASSWORD
            - name: MYSQL_DATABASE
              value: BigDataStackGDTDB
            - name: MYSQL_USER
              value: GDT
            - name: MYSQL_PASSWORD
              value: MYSQLPASSWORD
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: database-volume
              mountPath: /var/lib/mysql/
            - name: database-conf
              mountPath: /etc/mysql/conf.d/
          terminationMessagePolicy: File
          image: 'mysql:8.0.21'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
