# Realization Engine 'V1' Playbook, manually created by RichardM based on ATOS_Standalone_1596107817411.yaml


# --------------------------------------------------------------------------------------------------------------
# Top-Level Application Definition
# Is used for visualising distinct apps in the Realization Engine GUI 
# --------------------------------------------------------------------------------------------------------------

# Unique identifier for a user application, must be lower-case only and not contain spaces or underscores
appID: "atoswl" 

# Display name for the application
name: "Grocery Recommender Platform" 

# Display description for the application
description: "A grocery recommendation application. Contains load-generation, serving and visualization components" 

# Placeholders that are filled by the realization engine on registration
owner: "$owner$" # Openshift username to deploy this app as
namespace: "$namespace$" # Openshift Project / Kubernetes namespace to deploy this app within

# Type label list, normally this will just be 'playbook', this is used to trigger alternative parsing. inferMissingValues
# here tells the parser to fill in missing values from the application specification e.g. appID, owner, etc. as needed. 
types:
 - playbook
 - inferMissingValues

# --------------------------------------------------------------------------------------------------------------
# Object List
# This is a list of all of the Openshift and or Kubernetes Objects that are needed by this application. Currently,
# the following object types are supported:
# - DeploymentConfig,
# - Job,
# - Service,
# - Route,
# - Volume,
# - VolumeClaim,
# - Pod,
# - Secret,
# - ConfigMap,
# - ServiceAccount,
# - RoleBinding,
# - Role
#
# Each object add the following metadata added at the start of its definition
# - appID: The identifier of the app to tie this object to, if included in a Playbook we typically omit (added automatically)
# - owner: Openshift username to deploy this app as, typically omitted in playbooks (added automatically)
# - objectID: A unique identifier for this object
# - type: One of the above types, must correspond to what is specified within yamlSource
# - yamlSource: The normal yaml for the object, may contain placeholders
#
# Important notes:
# - metadata.name must be '$appID$-$objectID$-$instance$'
# - metadata.namespace must be '$namespace$'
# - Within a container, it is good practice to pass environment variable placeholders for owner, namespace, 
#   appID, objectID and instance, so that these can be used when exporting metric by that application (this
#   is how a running pod can be identified), the realization engine will fill these in when the object is
#   instantiated. 
# --------------------------------------------------------------------------------------------------------------
objects:
  # Deployment Config: recommendations-calculation
  - objectID: "recommendations-calculation"
    type: DeploymentConfig
    yamlSource:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      metadata:
        name: $appID$-$objectID$-$instance$
        namespace: $namespace$
        labels:
         - "Recommender"
         - "User Facing"
         - "Supports Replication"
         - "CPU Intensive"
      spec:
        replicas: 1
        strategy:
          resources: {}
        template:
          metadata:
            labels:
              jobconfig: $appID$-$objectID$-$instance$
          spec:
            containers:
             - name: recommendation
               image: "atos/recommendations_calculation:latest"
               ports: 
                - containerPort: 7070
                  protocol: "TCP"
               env:
                - name: "owner"
                  value: "$owner$"
                - name: "namespace"
                  value: "$namespace$"
                - name: "appID"
                  value: "$appID$"
                - name: "objectID"
                  value: "$objectID$"
                - name: "instance"
                  value: "$instance$"
               resources: 
                 limits:
                   cpu: "1000m"
                   memory: "2048Mi"
                 requests:
                   cpu: "1000m"
                   memory: "2048Mi"
               securityContext: {}
               serviceAccount: default
               imagePullPolicy: "Always"
            restartPolicy: "Always"
  
  # Service: srv-recommendation-ui
  - objectID: "srv-recommendation-ui"
    type: Service
    yamlSource:
      apiVersion: v1
      kind: Service
      metadata:
        name: $appID$-$objectID$-$instance$
        namespace: $namespace$
      spec:
        selector:
          jobconfig: $appID$-$objectID$-$instance$
        ports:
          - name: "web"
            protocol: "TCP"
            port: 7070
            targetPort: 7070
  
  # Route: route-recommendation-ui
  - objectID: "route-recommendation-ui"
    type: Route
    yamlSource:
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: $appID$-$objectID$-$instance$
        namespace: $namespace$
      spec:
        host: recommender-$namespace$.$hostExtension$
        to:
          kind: Service
          name: $serviceLookup$
          weight: 100
        port:
          targetPort: web
        wildcardPolicy: None


# --------------------------------------------------------------------------------------------------------------
# Metric List
# Provides definitions of named metrics that will be exported by the app components. This is mostly used for
# visualisation purposes within the realization engine, but are also checked against when defining Service
# Level Objectives (SLOs)
#
# A metric definition is comprised of
# - owner: typically omitted in playbooks (added automatically)
# - name: unique id for the metric
# - metricClassname: java class used to parse the values for this metric (usually 'Double')
# - summary: Human readable summary of the metric 
# - maximumValue: Maximum allowed value for this metric
# - minimumValue: Minimum allowed value for this metric
# - higherIsBetter: Is a higher number 'better' for this metric if used for evaluation
# - displayUnit: Display unit when showing/graphing the metric
# --------------------------------------------------------------------------------------------------------------
metrics:
  # requestsPerMinute
  - name: "requestsPerMinute"
    metricClassname: "Double"
    summary: "The number of atomic requests that the component is recieveing per minute"
    maximumValue: 1000000.0 # 
    minimumValue: 0.0
    higherIsBetter: True 
    displayUnit: "requests/min"
  # costPerHour  
  - name: "costPerHour"
    metricClassname: "Double"
    summary: "The cost of running this component per hour in US dollars." 
    maximumValue: 1000.0
    minimumValue: 0.0
    higherIsBetter: False
    displayUnit: "$/hour"
  # accuracy  
  - name: "accuracy"
    metricClassname: "Double"
    summary: "Recommendation using the accuracy metric, aggregated over requests." 
    maximumValue: 1.0
    minimumValue: 0.0
    higherIsBetter: True
    displayUnit: "Accuracy"
  # throughput  
  - name: "throughput"
    metricClassname: "Double"
    summary: "Throughput of the application (number of items processed per minute)." 
    maximumValue: 1000000.0
    minimumValue: 0.0
    higherIsBetter: True
    displayUnit: "processed/min"
  # responseTime  
  - name: "responseTime"
    metricClassname: "Double"
    summary: "Average delay between recieving a request and returning a response in miliseconds." 
    maximumValue: 1000000.0
    minimumValue: 0.0
    higherIsBetter: False
    displayUnit: "ms"

# --------------------------------------------------------------------------------------------------------------
# Service Level Objective List
# Defines an objective to be met by a particular component of the application. In practice, an slo links together
# an object definition of type DeploymentConfig or Job with a Metric, while also providing a target service level
# to reach
#
# A service level objective is comprised of:
# - appID: typically omitted in playbooks (added automatically)
# - owner: typically omitted in playbooks (added automatically)
# - namespace: typically omitted in playbooks (added automatically)
# - objectID: the object that the SLO is attached to
# - instance: the object instance to track (this is added automatically at deploy time via the 'AttachSLOs Operation')
# - sloIndex: the instance number of this SLO (is added automatically at deploy time via the 'AttachSLOs Operation')
# - metricName: the metric that the SLO is tracking
# - type: the comparison check to perform, e.g. "maximum" or "average"
# - value: the threshold to compare against
# - breachSeverity: if the check fails, at what severity (Info,Warning,Error,Alert) should the associated event be generated
# - isRequirement: Is this a requirement or is this a preference?
# --------------------------------------------------------------------------------------------------------------
slos:
  - objectID: "recommendations-calculation"
    metricName: "costPerHour"
    type: "maximum"
    value: 200
    breachSeverity: "Alert"
    isRequirement: True
  - objectID: "recommendations-calculation"
    metricName: "costPerHour"
    type: "maximum"
    value: 190
    breachSeverity: "Alert"
    isRequirement: False
  - objectID: "recommendations-calculation"
    metricName: "responseTime"
    type: "maximum"
    value: 500
    breachSeverity: "Alert"
    isRequirement: True
  - objectID: "recommendations-calculation"
    metricName: "responseTime"
    type: "maximum"
    value: 400
    breachSeverity: "Alert"
    isRequirement: False
  - objectID: "recommendations-calculation"
    metricName: "accuracy"
    type: "minimum"
    value: 0.89
    breachSeverity: "Alert"
    isRequirement: True
  - objectID: "recommendations-calculation"
    metricName: "accuracy"
    type: "minimum"
    value: 0.95
    breachSeverity: "Alert"
    isRequirement: False
  - objectID: "recommendations-calculation"
    metricName: "throughput"
    type: "minimum"
    value: 10000
    breachSeverity: "Alert"
    isRequirement: True
  - objectID: "recommendations-calculation"
    metricName: "throughput"
    type: "minimum"
    value: 100000
    breachSeverity: "Alert"
    isRequirement: False
    
# --------------------------------------------------------------------------------------------------------------
# Operation Sequence List
# Describes pre-defined 'actions' that can be performed to the user's application. An operation sequence is as
# its name suggests a series of operations that will be performed in sequence, which will normally alter objects
# registered to the realization engine and/or alter the state of the cluster. 
# 
# An operation sequence contains the following fields:
# - appID: typically omitted in playbooks (added automatically)
# - owner: typically omitted in playbooks (added automatically)
# - namespace: typically omitted in playbooks (added automatically)
# - sequenceID: a unique id for this operation sequence (within the app)
# - name: a name for the operation sequence, used for display
# - description: a description of what the operation sequence does, used for display
# - parameters: a map/dictionary of default parameters to use if not set elsewhere
# - operations: a list of operations to perform within the sequence
# - mode: a tag used to specify how the sequence should be processed (normally 'Continue', other options are 'Run' and 'RunIgnoreFailures')
# --------------------------------------------------------------------------------------------------------------
sequences:
  - sequenceID: "launch"
    name: "Launch Recommender Service"
    description: "Deploys a instance of the recommender framework and configures an assiociated service and route."
    parameters: {}
    operations:
      # Steps for creating the deployment config
      - className: Instantiate # Spawn a new copy from the template
        objectID: "recommendations-calculation"
        defineInstanceRef: "recDeploymentConfig"
      - className: SetSequenceParameters # Fill in any missing placeholders
        instanceRef: "recDeploymentConfig"
      - className: Apply # Create deployment config on the cluster
        instanceRef: "recDeploymentConfig"
      - className: WaitFor # Wait until the deployment config is reporting available
        instanceRef: "recDeploymentConfig"
        waitForStatus: "Available"
      # Now create the service
      - className: Instantiate # Spawn a new copy from the template
        objectID: "srv-recommendation-ui"
        defineInstanceRef: "newService"
      - className: Apply # Create the service on the cluster
        instanceRef: "newService"
      # Now create the route
      - className: ParameterFromObjectLookup # Generates a parameter value by querying the cluster state
        parameter: "serviceLookup"
        criteria: "$namespace$:service:$appID$-srv-recommendation-ui-.*"
        multipleMatches: "SelectFirst"
      - className: Instantiate # Spawn a new copy from the template
        objectID: "route-recommendation-ui"
        defineInstanceRef: "newRoute"
      - className: SetSequenceParameters # Fill in any missing placeholders (most notably 'serviceLookup' found above)
        instanceRef: "newRoute"
      - className: Apply # Create the route on the cluster
        instanceRef: "newRoute"
      # Finally attach all of the SLOs for the object
      - className: AttachSLOs # Looks up all SLOs registered and performs set-up for each for the object instance
        instanceRef: "recDeploymentConfig"
    mode: Continue
